version: '3'
services:
  jupyter:
    build: ./docker/jupyter
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
      #- 5678:5678
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
    restart: unless-stopped